csm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


admin.site.site_header = 'BRANCH INTERNATIONAL'
admin.site.index_title = 'Agent'
admin.site.site_title = 'CSM'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls'))
]

users/urls.py
from django.urls import path, re_path

from users.views import *

urlpatterns = [
    path('', get_user_query),
    path('success/', success_page, name='success'),
    re_path(r'^user/userquery/\d+/resolve', resolve_query, name='resolve_query'),
    re_path(r'^user/userquery/\d+/unresolve', unresolve_query, name='unresolve_query'),
    re_path(r'^user/userquery/\d+/transfer', transfer_query, name='transfer_query')
]

users/models.py
from email.policy import default
from django.db import models

# Create your models here.
URGENCY = (
    ('LOW', 'LOW'),
    ('MED', 'MED'),
    ('HIGH', 'HIGH')
)

STATUS = (
    ('Resolved', 'Resolved'),
    ('Assigned', 'Assigned'),
    ('Open', 'Open'),
)

class UserQuery(models.Model):
    userID = models.PositiveSmallIntegerField("User ID")
    timestamp = models.DateTimeField("Timestamp (UTC)", auto_now_add=True)
    messageBody = models.TextField("Message Body")
    urgency_status = models.CharField(max_length=20)
    resolved = models.CharField(max_length=255, choices=STATUS, default='Open')

    def get_urgency_status(self, query):
        message = self.messageBody.lower()
        keywords = ['loan', 'approval', 'process', 'disburse', 'when', 'why', 'reject', 'application', 'late', 'expunge', 'approve', 'can', '?', '']
        status = set(keywords).intersection(message.split())
        count = 0
        for word in status:
            count += message.split().count(word)

        count = len(set(keywords).intersection(message.split()))
        if count>2:
            return 'HIGH'
        elif count>1:
            return 'MEDIUM'
        return 'LOW'

    def save(self, *args, **kwargs):
        self.urgency_status = self.get_urgency_status(self.messageBody)
        super(UserQuery, self).save(*args, **kwargs)
        

class AgentResponse(models.Model):
    agent_name = models.CharField(max_length=255)
    userID = models.PositiveSmallIntegerField("User ID")
    queries_handled = models.JSONField(default=list)
    query_response = models.TextField()

users/forms.py
from django.forms import ModelForm
from django import forms
from users.models import UserQuery

CANNED_MESSAGES = [

]

class UserForm(ModelForm):
    class Meta:
        model = UserQuery
        fields = ['userID', 'messageBody']

class ResolveQuery(forms.Form):
    response = forms.CharField(required=True, widget=forms.Textarea)

users/views.py
from django.shortcuts import render
from .forms import UserForm, ResolveQuery
from django.http import HttpResponseRedirect
from .models import UserQuery, AgentResponse

# Create your views here.

def get_user_query(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/success/')
    else:
        form = UserForm()
    return render(request, 'form.html', {'form': form})


def success_page(request):
    return render(request, 'success.html')


def resolve_query(request):
    id = request.get_full_path().strip().split('/')[-2]
    query = UserQuery.objects.get(pk=id)
    query.resolved = 'Assigned'
    query.save()
    other_queries = UserQuery.objects.filter(userID=query.userID).exclude(pk=id).exclude(resolved='Resolved').order_by('-timestamp')

    if request.method == 'POST':
        form = ResolveQuery(request.POST)
        if form.is_valid():
            query.resolved = 'Resolved'
            query.save()
            response = form.cleaned_data['response']
            list_of_other_queries = request.POST.getlist('other')
            all_queries = [id] + list_of_other_queries
            UserQuery.objects.filter(id__in=list_of_other_queries).update(resolved='Resolved')

            agent_response = AgentResponse(agent_name = request.user.username,
            userID = query.userID,
            queries_handled = all_queries,
            query_response = response
            )

            agent_response.save()

            return HttpResponseRedirect('/admin/users/userquery')
    else:
        form = ResolveQuery()
    
    return render(request, 'admin/resolve_query.html', {'query': query, 'form': form, 'other_queries': other_queries})


def unresolve_query(request):
    id = request.get_full_path().strip().split('/')[-2]
    query = UserQuery.objects.filter(pk=id).update(resolved='Open')
    return HttpResponseRedirect('/admin/users/userquery')


def transfer_query(request):
    id = request.get_full_path().strip().split('/')[-2]
    query = UserQuery.objects.filter(pk=id).update(resolved='Open')
    return HttpResponseRedirect('/admin/users/userquery')

users/templates/form.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'form_style.css' %}">
    <title>User Query</title>
</head>
<body>
    <span class="dot dot1"></span>
    <span class="dot dot2"></span>
    <span class="dot dot3"></span>
    <span class="dot dot4"></span>
    <div class="container content">
        <div class="logo">
            <img style="height: 2.8rem;" class="transition-brightness" src="../static/imgs/logo.png">
        </div>
        <div class="card-container">
            <div class="card shadow border-dark form">
                <div class="card-body align-items-center">
                    <h2 class="text-center card-title card-header">QUERY FORM</h2>
                    <br>
                    <form method="post" enctype="multipart/form-data" class="row g-3 card-text">
                        {% csrf_token %}
                        {% load widget_tweaks %}
        
                        <div class="col-md-12">
                            <label for="id_userID" class="form-label">User ID:</label>
                            {{form.userID | add_class:"form-control"}}
                        </div>
        
                        <div class="col-md-12">
                            <label for="id_messageBody">Message Body:</label>
                            {{form.messageBody | add_class:"form-control"}}
                        </div>
        
                        <button type="submit" class="btn btn-primary btn-lg submit">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    
</body>
</html>

users/templates/success.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'success_style.css' %}">
    <title>Thank You</title>
</head>
<body>
    <span class="dot dot1"></span>
    <span class="dot dot2"></span>
    <span class="dot dot3"></span>
    <span class="dot dot4"></span>
    <div class="container content card-container">
        <div class="logo">
            <img style="height: 2.8rem;" class="transition-brightness" src="../static/imgs/logo.png">
        </div>
        <div class="card shadow border-dark text-center">
            <img class="card-img-top check" src="../static/imgs/check.png">
            <div class="card-body">
                <h1>Thank You!</h1>
                <h3>Your query has been received.</h3>
                <h6>Our team will look into it and revert back in 3-5 business days.</h6>                
            </div>
            <div class="card-footer text-muted">
                <h6>Submit another query <a href="/"> here.</a></h6>
            </div>
        </div>
    </div>
</body>
</html>